
services:
  outline:
    image: outlinewiki/outline:latest
    container_name: outline
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./uploads:/data/uploads
      - ./server/config/database.json:/app/server/config/database.json:ro

  postgres:
    image: postgres:13
    container_name: outline_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: outline
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6
    container_name: outline_redis
    restart: unless-stopped

